package com.geelydiagnostics.app

internal object EcarxSensorMetadata {
    val fields: Map<String, EcarxFieldMetadata> = mapOf(
        "SENSOR_TYPE_ABS" to EcarxFieldMetadata("Состояние ABS"),
        "SENSOR_TYPE_ABS_WARNING" to EcarxFieldMetadata(
            "Предупреждение ABS",
            values = mapOf(
                1058305 to "Предупреждение включено",
                1058306 to "FLSG (служебное состояние)",
                1058307 to "RESD (служебное состояние)",
                1058308 to "Предупреждение выключено",
            )
        ),
        "SENSOR_TYPE_ACCELERATOR_DEPTH" to EcarxFieldMetadata("Положение педали газа", unit = "%"),
        "SENSOR_TYPE_AIRBAG_STATUS_DRIVER" to EcarxFieldMetadata("Состояние подушки безопасности водителя"),
        "SENSOR_TYPE_AIRBAG_STATUS_PASSENGER" to EcarxFieldMetadata("Состояние подушки безопасности пассажира"),
        "SENSOR_TYPE_ALRM_STS" to EcarxFieldMetadata(
            "Состояние охранной системы",
            values = mapOf(
                2122497 to "Снято с охраны",
                2122498 to "На охране",
                2122499 to "Тревога активна",
            )
        ),
        "SENSOR_TYPE_AQI_AMBIENT" to EcarxFieldMetadata("AQI снаружи", unit = "AQI"),
        "SENSOR_TYPE_AQI_BACK_ROW" to EcarxFieldMetadata("AQI заднего ряда", unit = "AQI"),
        "SENSOR_TYPE_AQI_INDOOR" to EcarxFieldMetadata("AQI в салоне", unit = "AQI"),
        "SENSOR_TYPE_AQI_LEVEL_AMBIENT" to EcarxFieldMetadata(
            "Уровень загрязнения воздуха снаружи",
            values = mapOf(
                -1 to "Неизвестно",
                2106113 to "Без загрязнения",
                2106114 to "Низкое загрязнение",
                2106115 to "Среднее загрязнение",
                2106116 to "Высокое загрязнение",
                2106117 to "Очень высокое загрязнение",
                2106118 to "LOWER_POLLUTION (семантика названия требует проверки)",
            )
        ),
        "SENSOR_TYPE_AQI_LEVEL_BACK_ROW" to EcarxFieldMetadata("Уровень загрязнения воздуха заднего ряда"),
        "SENSOR_TYPE_AQI_LEVEL_INDOOR" to EcarxFieldMetadata("Уровень загрязнения воздуха в салоне"),
        "SENSOR_TYPE_BATTERY_CURRENT" to EcarxFieldMetadata("Ток аккумулятора", unit = "A"),
        "SENSOR_TYPE_BRAKE_DEPTH" to EcarxFieldMetadata("Положение педали тормоза", unit = "%"),
        "SENSOR_TYPE_BRAKE_FLUID_LEVEL" to EcarxFieldMetadata(
            "Уровень тормозной жидкости",
            values = mapOf(
                -1 to "Неизвестно",
                2098689 to "Норма",
                2098690 to "Низкий уровень",
            )
        ),
        "SENSOR_TYPE_BRAKE_PRESSURE" to EcarxFieldMetadata("Давление тормоза"),
        "SENSOR_TYPE_BRK_WARNING" to EcarxFieldMetadata(
            "Предупреждение тормозной системы",
            values = mapOf(
                1058049 to "Предупреждение включено",
                1058050 to "Предупреждение выключено",
            )
        ),
        "SENSOR_TYPE_CAR_MODE" to EcarxFieldMetadata(
            "Режим автомобиля",
            values = mapOf(
                -1 to "Неизвестно",
                2102273 to "Обычный режим",
                2102274 to "Заводской режим",
                2102275 to "Транспортировочный режим",
                2102276 to "Аварийный / crash-режим",
                2102277 to "Динамометрический стенд",
            )
        ),
        "SENSOR_TYPE_CAR_SPEED" to EcarxFieldMetadata("Скорость автомобиля", unit = "км/ч", rawToDisplayScale = 3.6f),
        "SENSOR_TYPE_CAR_SPEED_ACCELERATION" to EcarxFieldMetadata("Ускорение", unit = "м/с²"),
        "SENSOR_TYPE_CAR_SPEED_FROM_IPK" to EcarxFieldMetadata("Скорость от приборной панели", unit = "км/ч"),
        "SENSOR_TYPE_CO2_INDOOR" to EcarxFieldMetadata("CO₂ в салоне", unit = "ppm"),
        "SENSOR_TYPE_CO2_LEVEL_INDOOR" to EcarxFieldMetadata("Уровень CO₂ в салоне"),
        "SENSOR_TYPE_DAY_NIGHT" to EcarxFieldMetadata("Режим день/ночь"),
        "SENSOR_TYPE_DRIVER_TIREDNESS_STATUS" to EcarxFieldMetadata("Состояние усталости водителя"),
        "SENSOR_TYPE_ENDURANCE_MILEAGE" to EcarxFieldMetadata("Запас хода", unit = "км"),
        "SENSOR_TYPE_ENDURANCE_MILEAGE_EV" to EcarxFieldMetadata("Запас хода на электротяге", unit = "км"),
        "SENSOR_TYPE_ENDURANCE_MILEAGE_FUEL" to EcarxFieldMetadata("Запас хода на топливе", unit = "км"),
        "SENSOR_TYPE_ENGINE_COOLANT_LEVEL" to EcarxFieldMetadata("Уровень охлаждающей жидкости"),
        "SENSOR_TYPE_ENGINE_COOLANT_TEMPERATURE" to EcarxFieldMetadata("Температура охлаждающей жидкости", unit = "°C"),
        "SENSOR_TYPE_ENGINE_OIL_LEVEL" to EcarxFieldMetadata("Уровень моторного масла"),
        "SENSOR_TYPE_ENGINE_OIL_PERC" to EcarxFieldMetadata("Процентный показатель моторного масла", unit = "%"),
        "SENSOR_TYPE_ENGINE_START_STOP_STATE" to EcarxFieldMetadata("Состояние Start/Stop"),
        "SENSOR_TYPE_ENGINE_STATE" to EcarxFieldMetadata("Состояние двигателя"),
        "SENSOR_TYPE_ESC_WARNING" to EcarxFieldMetadata("Предупреждение ESC"),
        "SENSOR_TYPE_EV_BATTERY_LEVEL" to EcarxFieldMetadata("Уровень заряда тяговой батареи", unit = "%"),
        "SENSOR_TYPE_EV_BATTERY_STATE" to EcarxFieldMetadata("Состояние тяговой батареи"),
        "SENSOR_TYPE_EV_BATTERY_TEMPERATURE" to EcarxFieldMetadata("Температура тяговой батареи", unit = "°C"),
        "SENSOR_TYPE_EYE_BALL_TRACK_STATE" to EcarxFieldMetadata("Состояние отслеживания взгляда"),
        "SENSOR_TYPE_FUEL_LEVEL" to EcarxFieldMetadata("Уровень топлива", unit = "%"),
        "SENSOR_TYPE_GEAR" to EcarxFieldMetadata(
            "Передача",
            values = mapOf(
                -1 to "Неизвестно",
                2097665 to "1",
                2097666 to "2",
                2097667 to "3",
                2097668 to "4",
                2097669 to "5",
                2097670 to "6",
                2097671 to "7",
                2097672 to "8",
                2097673 to "9",
                2097674 to "10",
                2097680 to "N",
                2097696 to "D",
                2097712 to "P",
                2097728 to "R",
            )
        ),
        "SENSOR_TYPE_HANDBRAKE_STATE" to EcarxFieldMetadata("Стояночный тормоз"),
        "SENSOR_TYPE_HVSYSRLY_STS" to EcarxFieldMetadata("Состояние реле высоковольтной системы"),
        "SENSOR_TYPE_IGNITION_STATE" to EcarxFieldMetadata(
            "Зажигание",
            values = mapOf(
                2097409 to "Не определено",
                2097410 to "LOCK",
                2097411 to "Выключено",
                2097412 to "ACC",
                2097413 to "Включено",
                2097414 to "Запуск",
                2097415 to "Готов к движению / Driving",
            )
        ),
        "SENSOR_TYPE_LANE_DEPARTURE" to EcarxFieldMetadata("Выезд из полосы"),
        "SENSOR_TYPE_LIGHT" to EcarxFieldMetadata("Состояние наружного освещения"),
        "SENSOR_TYPE_MOTO_SPEED_FRONT" to EcarxFieldMetadata("Обороты переднего электромотора", unit = "об/мин"),
        "SENSOR_TYPE_MOTO_SPEED_REAR" to EcarxFieldMetadata("Обороты заднего электромотора", unit = "об/мин"),
        "SENSOR_TYPE_MOTO_TORQUE_FRONT" to EcarxFieldMetadata("Крутящий момент переднего электромотора", unit = "Н·м"),
        "SENSOR_TYPE_MOTO_TORQUE_REAR" to EcarxFieldMetadata("Крутящий момент заднего электромотора", unit = "Н·м"),
        "SENSOR_TYPE_ODOMETER" to EcarxFieldMetadata("Пробег", unit = "км"),
        "SENSOR_TYPE_PM25_AMBIENT" to EcarxFieldMetadata("PM2.5 снаружи", unit = "µg/m³"),
        "SENSOR_TYPE_PM25_BACK_ROW" to EcarxFieldMetadata("PM2.5 заднего ряда", unit = "µg/m³"),
        "SENSOR_TYPE_PM25_INDOOR" to EcarxFieldMetadata("PM2.5 в салоне", unit = "µg/m³"),
        "SENSOR_TYPE_PM25_LEVEL_AMBIENT" to EcarxFieldMetadata("Уровень PM2.5 снаружи"),
        "SENSOR_TYPE_PM25_LEVEL_BACK_ROW" to EcarxFieldMetadata("Уровень PM2.5 заднего ряда"),
        "SENSOR_TYPE_PM25_LEVEL_INDOOR" to EcarxFieldMetadata("Уровень PM2.5 в салоне"),
        "SENSOR_TYPE_PM25_STATE_AMBIENT" to EcarxFieldMetadata("Состояние датчика PM2.5 снаружи"),
        "SENSOR_TYPE_PM25_STATE_BACK_ROW" to EcarxFieldMetadata("Состояние датчика PM2.5 заднего ряда"),
        "SENSOR_TYPE_PM25_STATE_INDOOR" to EcarxFieldMetadata("Состояние датчика PM2.5 в салоне"),
        "SENSOR_TYPE_RAIN" to EcarxFieldMetadata("Значение датчика дождя"),
        "SENSOR_TYPE_RAIN_SENSOR_STATE" to EcarxFieldMetadata("Состояние датчика дождя"),
        "SENSOR_TYPE_REAR_WHEEL_ANGEL" to EcarxFieldMetadata("Угол поворота задних колёс", unit = "°"),
        "SENSOR_TYPE_ROLLBAR_POSITION_FRONT" to EcarxFieldMetadata("Положение переднего активного стабилизатора"),
        "SENSOR_TYPE_ROLLBAR_POSITION_REAR" to EcarxFieldMetadata("Положение заднего активного стабилизатора"),
        "SENSOR_TYPE_ROLLBAR_TORQUE_FRONT" to EcarxFieldMetadata("Крутящий момент переднего активного стабилизатора", unit = "Н·м"),
        "SENSOR_TYPE_ROLLBAR_TORQUE_REAR" to EcarxFieldMetadata("Крутящий момент заднего активного стабилизатора", unit = "Н·м"),
        "SENSOR_TYPE_RPM" to EcarxFieldMetadata("Обороты двигателя", unit = "об/мин"),
        "SENSOR_TYPE_SAFE_BELT_DRIVER" to EcarxFieldMetadata(
            "Ремень водителя",
            values = mapOf(
                -1 to "Неизвестно",
                2101761 to "Не пристёгнут",
                2101762 to "Пристёгнут",
            )
        ),
        "SENSOR_TYPE_SAFE_BELT_DRIVER_ORIGIN_STATUS" to EcarxFieldMetadata("Исходный статус ремня водителя"),
        "SENSOR_TYPE_SAFE_BELT_PASSENGER" to EcarxFieldMetadata("Ремень переднего пассажира"),
        "SENSOR_TYPE_SAFE_BELT_ROW2_CENTER" to EcarxFieldMetadata("Ремень второго ряда по центру"),
        "SENSOR_TYPE_SAFE_BELT_ROW2_LEFT" to EcarxFieldMetadata("Ремень второго ряда слева"),
        "SENSOR_TYPE_SAFE_BELT_ROW2_RIGHT" to EcarxFieldMetadata("Ремень второго ряда справа"),
        "SENSOR_TYPE_SEAT_OCCUPATION_STATUS_DRIVER" to EcarxFieldMetadata("Занятость сиденья водителя"),
        "SENSOR_TYPE_SEAT_OCCUPATION_STATUS_PASSENGER" to EcarxFieldMetadata("Занятость сиденья пассажира"),
        "SENSOR_TYPE_SEAT_OCCUPATION_STATUS_SECOND_ROW_LEFT" to EcarxFieldMetadata("Занятость второго ряда слева"),
        "SENSOR_TYPE_SEAT_OCCUPATION_STATUS_SECOND_ROW_RIGHT" to EcarxFieldMetadata("Занятость второго ряда справа"),
        "SENSOR_TYPE_SEAT_PRESSURE_DRIVER" to EcarxFieldMetadata("Давление/нагрузка на сиденье водителя"),
        "SENSOR_TYPE_SEAT_PRESSURE_PASSENGER" to EcarxFieldMetadata("Давление/нагрузка на сиденье пассажира"),
        "SENSOR_TYPE_SNSR_FR_WARNING" to EcarxFieldMetadata("Предупреждение датчика FR"),
        "SENSOR_TYPE_SNSR_LE_WARNING" to EcarxFieldMetadata("Предупреждение датчика LE"),
        "SENSOR_TYPE_SNSR_RE_WARNING" to EcarxFieldMetadata("Предупреждение датчика RE"),
        "SENSOR_TYPE_SNSR_RI_WARNING" to EcarxFieldMetadata("Предупреждение датчика RI"),
        "SENSOR_TYPE_STATUS_TWLIBRISTS" to EcarxFieldMetadata("Статус TWLIBRISTS"),
        "SENSOR_TYPE_STEERING_WHEEL_ANGLE" to EcarxFieldMetadata("Угол руля", unit = "°"),
        "SENSOR_TYPE_STEERING_WHEEL_ANGLE_SPEED" to EcarxFieldMetadata("Скорость вращения руля", unit = "°/с"),
        "SENSOR_TYPE_TEMPERATURE_AMBIENT" to EcarxFieldMetadata("Температура снаружи", unit = "°C"),
        "SENSOR_TYPE_TEMPERATURE_INDOOR" to EcarxFieldMetadata("Температура в салоне", unit = "°C"),
        "SENSOR_TYPE_TIREDNESS_DRIVING_STATE" to EcarxFieldMetadata("Состояние контроля усталости при движении"),
        "SENSOR_TYPE_TOO_CLOSE_TO_FRONT_CAR" to EcarxFieldMetadata("Опасно малая дистанция до автомобиля впереди"),
        "SENSOR_TYPE_VEHICLE_WEIGHT" to EcarxFieldMetadata("Масса автомобиля", unit = "кг"),
        "SENSOR_TYPE_VEH_MTN_STATE" to EcarxFieldMetadata("Состояние движения автомобиля"),
        "SENSOR_TYPE_WARN_ENGINE_COOLANT_SYSTEM_FAULT" to EcarxFieldMetadata("Неисправность системы охлаждения двигателя"),
        "SENSOR_TYPE_WARN_ENGINE_COOLANT_TEMP_HIGH" to EcarxFieldMetadata("Высокая температура охлаждающей жидкости"),
        "SENSOR_TYPE_WARN_ENGINE_OIL_PRESSURE" to EcarxFieldMetadata("Предупреждение по давлению моторного масла"),
        "SENSOR_TYPE_WARN_ENGINE_OIL_SYSTEM_FAULT" to EcarxFieldMetadata("Неисправность системы моторного масла"),
        "SENSOR_TYPE_WARN_EV_BATTERY_LOW" to EcarxFieldMetadata("Низкий заряд тяговой батареи"),
        "SENSOR_TYPE_WARN_FUEL_RED" to EcarxFieldMetadata("Низкий уровень топлива"),
        "SENSOR_TYPE_WARN_STEERING_ASSISTANCE_FAULT" to EcarxFieldMetadata("Неисправность усилителя рулевого управления"),
        "SENSOR_TYPE_WARN_TRANSMISSION_SYSTEM_FAULT" to EcarxFieldMetadata("Неисправность трансмиссии"),
        "SENSOR_TYPE_WARN_TRANSMISSION_TEMP_HIGH" to EcarxFieldMetadata("Высокая температура трансмиссии"),
        "SETTING_FUNC_TELM_PHOTO_SWT" to EcarxFieldMetadata("Переключатель телематической фотосъёмки"),
        "SETTING_FUNC_VSTD_CTRL_REQ" to EcarxFieldMetadata("Запрос управления VSTD"),
    )
}
