package com.geelydiagnostics.app

internal object EcarxFunctionMetadata {
    val fields: Map<String, EcarxFieldMetadata> = mapOf(
        "BCM_FUNC_ALL_READING_LIGHTS_SWITCH" to EcarxFieldMetadata("Все плафоны освещения салона"),
        "BCM_FUNC_CHARGING_CAP" to EcarxFieldMetadata("Крышка зарядного порта"),
        "BCM_FUNC_CHILD_SAFETY_LOCK" to EcarxFieldMetadata("Детский замок"),
        "BCM_FUNC_CUSTOM_KEY" to EcarxFieldMetadata(
            title = "Назначение пользовательской кнопки",
            values = mapOf(
                1 to "Камера 360°",
                101 to "Автопарковка",
                5 to "Добавить в избранное",
                3 to "Полноэкранная карта DIM",
                102 to "Режим движения",
                0 to "Видеорегистратор DVR",
                99 to "Громкая связь / внешний динамик",
                2 to "Навигация",
                6 to "Регулировка зеркал",
                4 to "Звук",
                100 to "Открытие багажника",
            )
        ),
        "BCM_FUNC_DIM_ZONE_A_WARNING" to EcarxFieldMetadata("Предупреждение о затемнённой зоне A"),
        "BCM_FUNC_DISPLAY_ONOFF" to EcarxFieldMetadata("Питание/подсветка BCM-подсистем"),
        "BCM_FUNC_DOOR" to EcarxFieldMetadata(
            title = "Управление дверью",
            values = mapOf(
                0 to "Закрыть",
                1 to "Открыть",
                553779457 to "Пауза",
            )
        ),
        "BCM_FUNC_DOOR_LOCK" to EcarxFieldMetadata("Замки дверей"),
        "BCM_FUNC_DOOR_LOCK_FAULT" to EcarxFieldMetadata("Неисправность замка двери"),
        "BCM_FUNC_DOOR_STATUS" to EcarxFieldMetadata("Состояние дверей"),
        "BCM_FUNC_FOLD_REAR_MIRROR" to EcarxFieldMetadata("Складывание наружных зеркал"),
        "BCM_FUNC_FPL_FOLLOW_DRL" to EcarxFieldMetadata(
            title = "Связь ближнего света с ДХО",
            values = mapOf(
                555745537 to "Режим 1",
                555745538 to "Режим 2",
            )
        ),
        "BCM_FUNC_FUEL_CAP" to EcarxFieldMetadata("Лючок топливного бака"),
        "BCM_FUNC_LIGHT_ATMOSPHERE_LAMPS" to EcarxFieldMetadata("Атмосферная подсветка салона"),
        "BCM_FUNC_LIGHT_FRONT_FOG_LAMPS" to EcarxFieldMetadata("Передние противотуманные фары"),
        "BCM_FUNC_LIGHT_HAZARD_FLASHERS" to EcarxFieldMetadata("Аварийная сигнализация"),
        "BCM_FUNC_LIGHT_LEFT_TRUN_SIGNAL" to EcarxFieldMetadata("Левый указатель поворота"),
        "BCM_FUNC_LIGHT_READING_LIGHT" to EcarxFieldMetadata("Индивидуальный плафон"),
        "BCM_FUNC_LIGHT_REAR_FOG_LAMPS" to EcarxFieldMetadata("Задний противотуманный фонарь"),
        "BCM_FUNC_LIGHT_RIGHT_TRUN_SIGNAL" to EcarxFieldMetadata("Правый указатель поворота"),
        "BCM_FUNC_LIGHT_WELCOME_LIGHT" to EcarxFieldMetadata("Приветственная подсветка"),
        "BCM_FUNC_POWER_ONOFF" to EcarxFieldMetadata("Питание BCM-подсистем"),
        "BCM_FUNC_REAR_MIRROR_ADJUST" to EcarxFieldMetadata("Регулировка наружных зеркал"),
        "BCM_FUNC_STEERING_WHEEL_ADJUST" to EcarxFieldMetadata("Регулировка рулевой колонки"),
        "BCM_FUNC_SUNCURT_CLS_BTN" to EcarxFieldMetadata("Закрытие солнцезащитной шторки"),
        "BCM_FUNC_SUNCURT_OPEN_BTN" to EcarxFieldMetadata("Открытие солнцезащитной шторки"),
        "BCM_FUNC_SUNROOF_CLS_BTN" to EcarxFieldMetadata("Закрытие люка"),
        "BCM_FUNC_SUNROOF_ININ_SWITCH" to EcarxFieldMetadata("Направление движения люка"),
        "BCM_FUNC_SUNROOF_OPEN_BTN" to EcarxFieldMetadata("Открытие люка"),
        "BCM_FUNC_SUNROOF_TILT" to EcarxFieldMetadata("Приоткрытие люка"),
        "BCM_FUNC_WASHER" to EcarxFieldMetadata("Омыватель ветрового стекла"),
        "BCM_FUNC_WINDOW" to EcarxFieldMetadata(
            title = "Управление стеклоподъёмником",
            values = mapOf(
                0 to "Закрыть",
                1 to "Открыть",
                553844993 to "Пауза",
                553844994 to "Половина",
                553844995 to "Открытие / пауза",
                553844996 to "Закрытие / пауза",
            )
        ),
        "BCM_FUNC_WINDOW_CURRENT_POS" to EcarxFieldMetadata("Текущее положение стекла"),
        "BCM_FUNC_WINDOW_MOVING_STATE" to EcarxFieldMetadata("Состояние движения стекла"),
        "BCM_FUNC_WINDOW_POS" to EcarxFieldMetadata("Целевая позиция стекла"),
        "BCM_FUNC_WIPER" to EcarxFieldMetadata(
            title = "Стеклоочиститель",
            values = mapOf(
                0 to "Выключено",
                553713921 to "Авто",
                553713922 to "Низкая скорость",
                553713923 to "Высокая скорость",
                553713924 to "Прерывистый режим",
            )
        ),
        "DM_FUNC_DM_CUSTOM_BPF" to EcarxFieldMetadata("Dm пользовательский bpf"),
        "DM_FUNC_DM_CUSTOM_CLIMATE_MODE" to EcarxFieldMetadata("Климат в пользовательском режиме"),
        "DM_FUNC_DM_CUSTOM_DRIVER_INFO" to EcarxFieldMetadata("Dm пользовательский водитель info"),
        "DM_FUNC_DM_CUSTOM_EN_START_STOP" to EcarxFieldMetadata("Start/Stop в пользовательском режиме"),
        "DM_FUNC_DM_CUSTOM_INFOR_THEME" to EcarxFieldMetadata("Dm пользовательский infor theme"),
        "DM_FUNC_DM_CUSTOM_INTERIOR_LIGHT" to EcarxFieldMetadata("Подсветка салона в пользовательском режиме"),
        "DM_FUNC_DM_CUSTOM_PROPULSION_SYS" to EcarxFieldMetadata("Силовая установка в пользовательском режиме"),
        "DM_FUNC_DM_CUSTOM_RAB" to EcarxFieldMetadata("Dm пользовательский rab"),
        "DM_FUNC_DM_CUSTOM_STEERING_WHEEL_FEEL" to EcarxFieldMetadata("Усилие руля в пользовательском режиме"),
        "DM_FUNC_DM_CUSTOM_SUSPENSION_MODE" to EcarxFieldMetadata("Подвеска в пользовательском режиме"),
        "DM_FUNC_DRIVE_MODE_SELECT" to EcarxFieldMetadata(
            title = "Выбранный режим движения",
            values = mapOf(
                570491137 to "Eco",
                570491138 to "Comfort",
                570491139 to "Dynamic / Sport",
                570491140 to "XC",
                570491141 to "HDC",
                570491142 to "Pure",
                570491143 to "Hybrid",
                570491144 to "Power",
                570491145 to "Snow",
                570491146 to "Mud",
                570491147 to "Rock",
                570491148 to "PHEV",
                570491149 to "Sand",
                570491150 to "AWD",
                570491151 to "Save",
                570491152 to "Eco HEV/PHEV",
                570491153 to "Normal",
                570491154 to "eAWD",
                570491155 to "Off-road",
                570491156 to "Eco+",
                570491157 to "Sport+",
                570491158 to "Adaptive",
                570491159 to "Start type 18",
                570491160 to "Start type 72",
                570491161 to "Start type 79",
                570491162 to "Start type 97",
                570491200 to "Custom",
            )
        ),
        "DM_FUNC_STEERING_WHEEL_FEEL_SYNC_DRIVEMODE" to EcarxFieldMetadata("Синхронизация усилия руля с режимом движения"),
        "FUNC_UNIT_AVG_FUEL" to EcarxFieldMetadata("Единица среднего расхода топлива"),
        "FUNC_UNIT_DATE_FORMAT" to EcarxFieldMetadata("Формат даты"),
        "FUNC_UNIT_DRIVEN_DISTANCE" to EcarxFieldMetadata("Единица расстояния"),
        "FUNC_UNIT_SPEED" to EcarxFieldMetadata("Единица скорости"),
        "FUNC_UNIT_TEMPERATURE" to EcarxFieldMetadata("Единица температуры"),
        "FUNC_UNIT_TIME_INDICATION" to EcarxFieldMetadata("Формат времени"),
        "FUNC_UNIT_TIRE_PRESSURE" to EcarxFieldMetadata("Единица давления в шинах"),
        "HVAC_FUNC_AC" to EcarxFieldMetadata("Кондиционер A/C"),
        "HVAC_FUNC_AC_MAX" to EcarxFieldMetadata("Максимальное охлаждение A/C MAX"),
        "HVAC_FUNC_AIR_FRAGRANCE" to EcarxFieldMetadata("Ароматизация воздуха"),
        "HVAC_FUNC_AIR_FRAGRANCE_LEVEL" to EcarxFieldMetadata(
            title = "Интенсивность ароматизации",
            values = mapOf(
                0 to "Выключено",
                269157121 to "Уровень 1",
                269157122 to "Уровень 2",
                269157123 to "Уровень 3",
            )
        ),
        "HVAC_FUNC_AIR_FRAGRANCE_LOW" to EcarxFieldMetadata("Air fragrance low"),
        "HVAC_FUNC_AIR_FRAGRANCE_SLOT" to EcarxFieldMetadata(
            title = "Слот ароматизатора",
            values = mapOf(
                269157377 to "Слот 1",
                269157378 to "Слот 2",
                269157379 to "Слот 3",
                269157380 to "Слот 4",
                269157381 to "Слот 5",
            )
        ),
        "HVAC_FUNC_AIR_FRAGRANCE_TYPE" to EcarxFieldMetadata(
            title = "Тип аромата",
            values = mapOf(
                0 to "Выключено",
                269156865 to "Роза",
                269156866 to "Лилия",
                269156867 to "Лаванда",
                269156868 to "Лунцзин",
                269156869 to "Сандал",
                269156870 to "Жасмин",
            )
        ),
        "HVAC_FUNC_AIR_FRAGRANCE_TYPE_ID" to EcarxFieldMetadata("Air fragrance тип id"),
        "HVAC_FUNC_AI_POWER" to EcarxFieldMetadata("Ai энергосбережение"),
        "HVAC_FUNC_AQS_STATUS" to EcarxFieldMetadata("Aqs status"),
        "HVAC_FUNC_AUTO" to EcarxFieldMetadata("Автоматический режим климата"),
        "HVAC_FUNC_AUTOMATIC_VENTILATION_DRY" to EcarxFieldMetadata("Автоматический ventilation dry"),
        "HVAC_FUNC_AUTO_CLOSE_WINDOW_REMIND" to EcarxFieldMetadata("Автоматический закрытие окно remind"),
        "HVAC_FUNC_AUTO_CLOSE_WINDOW_REMIND_REQUEST" to EcarxFieldMetadata("Автоматический закрытие окно remind запрос"),
        "HVAC_FUNC_AUTO_CONTROL" to EcarxFieldMetadata("Автоматический управление"),
        "HVAC_FUNC_AUTO_CZIS" to EcarxFieldMetadata("Автоматический czis"),
        "HVAC_FUNC_AUTO_DEFROST_CONFIRM" to EcarxFieldMetadata("Автоматический defrost confirm"),
        "HVAC_FUNC_AUTO_DEFROST_FRONT" to EcarxFieldMetadata("Автоматический defrost передний"),
        "HVAC_FUNC_AUTO_DEFROST_REAR" to EcarxFieldMetadata("Автоматический defrost задний"),
        "HVAC_FUNC_AUTO_DEFROST_REQUEST" to EcarxFieldMetadata("Автоматический defrost запрос"),
        "HVAC_FUNC_AUTO_FAN_SETTING" to EcarxFieldMetadata(
            title = "Интенсивность вентилятора в AUTO",
            values = mapOf(
                268567041 to "Тихо",
                268567042 to "Нормально",
                268567043 to "Интенсивно",
                268567044 to "Очень тихо",
                268567045 to "Очень интенсивно",
            )
        ),
        "HVAC_FUNC_AUTO_FAN_SPEED_HARD_KEY" to EcarxFieldMetadata("Автоматический fan speed hard ключ"),
        "HVAC_FUNC_AUTO_ION" to EcarxFieldMetadata("Автоматический ion"),
        "HVAC_FUNC_AUTO_ION_CONFIRM" to EcarxFieldMetadata("Автоматический ion confirm"),
        "HVAC_FUNC_AUTO_ION_REQUEST" to EcarxFieldMetadata("Автоматический ion запрос"),
        "HVAC_FUNC_AUTO_REFRESHING_FRAGRANCE" to EcarxFieldMetadata("Автоматический refreshing fragrance"),
        "HVAC_FUNC_AUTO_SEAT_HEATING" to EcarxFieldMetadata(
            title = "Автоматический сиденье heating",
            values = mapOf(
                0 to "Выключено",
                268764417 to "Уровень 1",
                268764418 to "Уровень 2",
                268764419 to "Уровень 3",
            )
        ),
        "HVAC_FUNC_AUTO_SEAT_HEATING_TIME" to EcarxFieldMetadata(
            title = "Автоматический сиденье heating время",
            values = mapOf(
                0 to "Выключено",
                268764673 to "Время 1",
                268764674 to "Время 2",
                268764675 to "Время 3",
                268764676 to "Время 4",
            )
        ),
        "HVAC_FUNC_AUTO_SEAT_MASSAGE_TIME" to EcarxFieldMetadata(
            title = "Автоматический сиденье massage время",
            values = mapOf(
                0 to "Выключено",
                268765441 to "Время 1",
                268765442 to "Время 2",
                268765443 to "Время 3",
            )
        ),
        "HVAC_FUNC_AUTO_SEAT_VENTILATION_TIME" to EcarxFieldMetadata(
            title = "Автоматический сиденье ventilation время",
            values = mapOf(
                0 to "Выключено",
                268764161 to "Время 1",
                268764162 to "Время 2",
                268764163 to "Время 3",
                268764164 to "Время 4",
            )
        ),
        "HVAC_FUNC_AUTO_STEERING_WHEEL_HEAT" to EcarxFieldMetadata(
            title = "Автоматический рулевое управление руль нагрев",
            values = mapOf(
                269025793 to "Низкий",
                269025794 to "Средний",
                269025795 to "Высокий",
            )
        ),
        "HVAC_FUNC_AUTO_STEERING_WHEEL_HEAT_SWITCH" to EcarxFieldMetadata("Автоматический рулевое управление руль нагрев переключатель"),
        "HVAC_FUNC_AUTO_STEERING_WHEEL_HEAT_TIME" to EcarxFieldMetadata(
            title = "Автоматический рулевое управление руль нагрев время",
            values = mapOf(
                0 to "Выключено",
                269026049 to "Время 1",
                269026050 to "Время 2",
                269026051 to "Время 3",
            )
        ),
        "HVAC_FUNC_BLOWING_MODE" to EcarxFieldMetadata(
            title = "Направление обдува",
            values = mapOf(
                0 to "Выключено",
                268894465 to "В лицо",
                268894466 to "В ноги",
                268894467 to "В лицо и ноги",
                268894468 to "На лобовое стекло",
                268894469 to "В лицо и на стекло",
                268894470 to "В ноги и на стекло",
                268894471 to "Все направления",
                268894472 to "Автоматически",
            )
        ),
        "HVAC_FUNC_BLOWING_MODE_HARD_KEY" to EcarxFieldMetadata("Blowing режим hard ключ"),
        "HVAC_FUNC_CIRCULATION" to EcarxFieldMetadata("Рециркуляция воздуха"),
        "HVAC_FUNC_CIRCULATION_LONG_TOUCH" to EcarxFieldMetadata("Circulation long touch"),
        "HVAC_FUNC_CIRCULATION_TIMER" to EcarxFieldMetadata("Circulation timer"),
        "HVAC_FUNC_CLIMATE_HARDKEY_SOUND" to EcarxFieldMetadata("Climate hardkey звук"),
        "HVAC_FUNC_CLIMATE_LOCK" to EcarxFieldMetadata("Climate замок"),
        "HVAC_FUNC_CLIMATE_ZONE" to EcarxFieldMetadata("Climate zone"),
        "HVAC_FUNC_CO2_HIGHER_CONFIRM" to EcarxFieldMetadata("Co2 higher confirm"),
        "HVAC_FUNC_DEFROST_FRONT" to EcarxFieldMetadata("Обогрев/обдув лобового стекла"),
        "HVAC_FUNC_DEFROST_FRONT_MAX" to EcarxFieldMetadata("Defrost передний максимум"),
        "HVAC_FUNC_DEFROST_REAR" to EcarxFieldMetadata("Обогрев заднего стекла"),
        "HVAC_FUNC_DIRECTION_MODE" to EcarxFieldMetadata("Направление режим"),
        "HVAC_FUNC_DISPLAY_WINDOW_TAB" to EcarxFieldMetadata("Отображение окно tab"),
        "HVAC_FUNC_ECO_SWITCH" to EcarxFieldMetadata("Экономичный режим климата"),
        "HVAC_FUNC_ELECTRICAL_AIR_VENT" to EcarxFieldMetadata("Electrical air vent"),
        "HVAC_FUNC_FAN_SPEED" to EcarxFieldMetadata("Скорость вентилятора"),
        "HVAC_FUNC_FAN_SPEED_BLOWER" to EcarxFieldMetadata("Fan speed blower"),
        "HVAC_FUNC_FAN_SPEED_HARD_KEY" to EcarxFieldMetadata("Fan speed hard ключ"),
        "HVAC_FUNC_FILTER_ELEMENT_LIFE" to EcarxFieldMetadata("Ресурс салонного фильтра"),
        "HVAC_FUNC_G_CLEAN" to EcarxFieldMetadata("G очистка"),
        "HVAC_FUNC_INTELLIGENT_DEODORIZATION" to EcarxFieldMetadata("Intelligent deodorization"),
        "HVAC_FUNC_INTELLIGENT_RECOMMENDATION" to EcarxFieldMetadata("Intelligent recommendation"),
        "HVAC_FUNC_IONIZER_CLS_WIN_POPUP" to EcarxFieldMetadata("Ionizer cls win всплывающее окно"),
        "HVAC_FUNC_IONIZER_CLS_WIN_POPUP_SETTING" to EcarxFieldMetadata("Ionizer cls win всплывающее окно setting"),
        "HVAC_FUNC_IONS_SWITCH" to EcarxFieldMetadata("Ионизатор"),
        "HVAC_FUNC_OVERHEAT_PROTECTION" to EcarxFieldMetadata("Overheat защита"),
        "HVAC_FUNC_POST_CLIMATISATION" to EcarxFieldMetadata("Климат после поездки"),
        "HVAC_FUNC_POWER" to EcarxFieldMetadata("Климатическая установка"),
        "HVAC_FUNC_POWER_VR" to EcarxFieldMetadata("Энергосбережение vr"),
        "HVAC_FUNC_PRE_CLIMATISATION" to EcarxFieldMetadata("Предварительное кондиционирование"),
        "HVAC_FUNC_REFRESHING_FRAGRANCE_POP" to EcarxFieldMetadata("Refreshing fragrance pop"),
        "HVAC_FUNC_RESET_FILTER_ELEMENT_LIFE" to EcarxFieldMetadata("Сброс ресурса салонного фильтра"),
        "HVAC_FUNC_SEAT_HEATING" to EcarxFieldMetadata("Подогрев сиденья"),
        "HVAC_FUNC_SEAT_HEATING_LVLAUTO" to EcarxFieldMetadata("Сиденье heating lvlauto"),
        "HVAC_FUNC_SEAT_MASSAGE" to EcarxFieldMetadata("Массаж сиденья"),
        "HVAC_FUNC_SEAT_MASSAGE_PROGRAM" to EcarxFieldMetadata("Сиденье massage program"),
        "HVAC_FUNC_SEAT_MASSAGE_SWITCH" to EcarxFieldMetadata("Сиденье massage переключатель"),
        "HVAC_FUNC_SEAT_VENTILATION" to EcarxFieldMetadata("Вентиляция сиденья"),
        "HVAC_FUNC_SEAT_VENTILATION_LVLAUTO" to EcarxFieldMetadata("Сиденье ventilation lvlauto"),
        "HVAC_FUNC_STEERING_WHEEL_HEAT" to EcarxFieldMetadata("Подогрев рулевого колеса"),
        "HVAC_FUNC_SWEEPING_MODE" to EcarxFieldMetadata("Sweeping режим"),
        "HVAC_FUNC_TEMP" to EcarxFieldMetadata("Температура климатической зоны"),
        "HVAC_FUNC_TEMP_DUAL" to EcarxFieldMetadata("Раздельная температура климатических зон"),
        "SETTING_DHU_FAST_START_MODE" to EcarxFieldMetadata("Dhu fast старт режим"),
        "SETTING_FUNC_ABNORMAL_VEHICLE_ALARM" to EcarxFieldMetadata("Нештатного автомобиля предупреждение"),
        "SETTING_FUNC_ABNORMAL_VEHICLE_ALARM_MODE" to EcarxFieldMetadata("Нештатного автомобиля предупреждение режим"),
        "SETTING_FUNC_AMBIENCE_LIGHT_BOTZONES" to EcarxFieldMetadata("Ambience свет нижние зоны"),
        "SETTING_FUNC_AMBIENCE_LIGHT_BRIGHTNESS_DRIVING" to EcarxFieldMetadata("Яркость подсветки в движении"),
        "SETTING_FUNC_AMBIENCE_LIGHT_BRIGHTNESS_STATIONARY" to EcarxFieldMetadata("Яркость подсветки на стоянке"),
        "SETTING_FUNC_AMBIENCE_LIGHT_COLOR_SET" to EcarxFieldMetadata("Цвет атмосферной подсветки"),
        "SETTING_FUNC_AMBIENCE_LIGHT_COLOR_TYPE" to EcarxFieldMetadata("Ambience свет цвет тип"),
        "SETTING_FUNC_AMBIENCE_LIGHT_EXPERIENCE" to EcarxFieldMetadata(
            title = "Режим атмосферной подсветки",
            values = mapOf(
                537526529 to "Полный",
                537526530 to "Пользовательский",
            )
        ),
        "SETTING_FUNC_AMBIENCE_LIGHT_INTERACTIVE_EFFECT" to EcarxFieldMetadata("Ambience свет интерактивный эффект"),
        "SETTING_FUNC_AMBIENCE_LIGHT_MAINCOLOR" to EcarxFieldMetadata(
            title = "Основной режим/цвет атмосферной подсветки",
            values = mapOf(
                0 to "Выключено",
                537526785 to "Тема",
                537526786 to "Режим движения",
                537526787 to "Заданный цвет",
                537526788 to "Музыка",
                537526789 to "Плавный / non-polar",
                537526790 to "Дыхание",
                537526791 to "По скорости",
                537526792 to "По погоде",
                537526793 to "По температуре",
            )
        ),
        "SETTING_FUNC_AMBIENCE_LIGHT_MAINZONES" to EcarxFieldMetadata("Ambience свет основные зоны"),
        "SETTING_FUNC_AMBIENCE_LIGHT_TOPZONES" to EcarxFieldMetadata("Ambience свет верхние зоны"),
        "SETTING_FUNC_ARTIFICIAL_SOUND_PREVIEW" to EcarxFieldMetadata("Предпрослушивание искусственного звука"),
        "SETTING_FUNC_ARTIFICIAL_SOUND_SWITCH" to EcarxFieldMetadata("Искусственный звук автомобиля"),
        "SETTING_FUNC_ARTIFICIAL_SOUND_TYPE" to EcarxFieldMetadata(
            title = "Тип искусственного звука автомобиля",
            values = mapOf(
                0 to "Выключено",
                538575873 to "Тип 1",
                538575874 to "Тип 2",
                538575875 to "Тип 3",
                538575876 to "Тип 4",
                538575877 to "Тип 5",
                538575878 to "Тип 6",
                538575879 to "Тип 7",
                538575880 to "Тип 8",
            )
        ),
        "SETTING_FUNC_AUDIBLE_LOCKING_FEEDBACK" to EcarxFieldMetadata("Звуковое подтверждение запирания"),
        "SETTING_FUNC_AUTONOMOUS_EMERGENCY_BRAKING" to EcarxFieldMetadata("Автоматическое экстренное торможение"),
        "SETTING_FUNC_AUTO_CLOSE_ROOF_RAINY" to EcarxFieldMetadata("Автозакрытие люка при дожде"),
        "SETTING_FUNC_AUTO_CLOSE_WINDOW" to EcarxFieldMetadata(
            title = "Автоматическое закрытие окон",
            values = mapOf(
                0 to "Выключено",
                537396225 to "При запирании автомобиля",
                537396226 to "Долгое нажатие ключа",
            )
        ),
        "SETTING_FUNC_AUTO_HOLD" to EcarxFieldMetadata("Auto Hold"),
        "SETTING_FUNC_AUTO_REAR_WIPING" to EcarxFieldMetadata("Автоматический задний дворник"),
        "SETTING_FUNC_AUTO_SHOW_MODE" to EcarxFieldMetadata("Автоматический показ режим"),
        "SETTING_FUNC_AUTO_SHOW_MODE_ENTER_CONDITIONS" to EcarxFieldMetadata("Автоматический показ режим вход условия"),
        "SETTING_FUNC_AUTO_SHOW_MODE_ICON" to EcarxFieldMetadata("Автоматический показ режим значок"),
        "SETTING_FUNC_AUTO_SHOW_MODE_POPUP" to EcarxFieldMetadata("Автоматический показ режим всплывающее окно"),
        "SETTING_FUNC_AUTO_SHOW_MODE_TEXT" to EcarxFieldMetadata(
            title = "Автоматический показ режим текст",
            values = mapOf(
                0 to "Обычный текст",
                1 to "Скрыть / false",
                2 to "Передача",
            )
        ),
        "SETTING_FUNC_AUTO_TRAILER_LAMP_CHECK" to EcarxFieldMetadata("Автоматическая проверка фонарей прицепа"),
        "SETTING_FUNC_AVAS_SOUND_TYPE" to EcarxFieldMetadata("Avas звук тип"),
        "SETTING_FUNC_AVAS_SOUND_TYPE_NAME" to EcarxFieldMetadata("Avas звук тип название"),
        "SETTING_FUNC_AVAS_SOUND_TYPE_PATH" to EcarxFieldMetadata("Avas звук тип путь"),
        "SETTING_FUNC_AVAS_SWITCH" to EcarxFieldMetadata("Avas переключатель"),
        "SETTING_FUNC_AVAS_VOLUME" to EcarxFieldMetadata("Avas громкость"),
        "SETTING_FUNC_BLIND_CAMERA_SYNC_RT_TURN" to EcarxFieldMetadata("Слепая зона камера синхронизация rt поворот"),
        "SETTING_FUNC_BREATH_SCREEN_MODE" to EcarxFieldMetadata("Дыхание экран режим"),
        "SETTING_FUNC_BRIGHTNESS_DAY" to EcarxFieldMetadata("Яркость днём"),
        "SETTING_FUNC_BRIGHTNESS_MAX" to EcarxFieldMetadata("Максимальная яркость"),
        "SETTING_FUNC_BRIGHTNESS_MIN" to EcarxFieldMetadata("Минимальная яркость"),
        "SETTING_FUNC_BRIGHTNESS_NIGHT" to EcarxFieldMetadata("Яркость ночью"),
        "SETTING_FUNC_BRIGHTNESS_STEP" to EcarxFieldMetadata("Шаг яркости"),
        "SETTING_FUNC_CAR_LOCATOR" to EcarxFieldMetadata("Поиск автомобиля"),
        "SETTING_FUNC_CAR_LOCATOR_REMINDER_MODE" to EcarxFieldMetadata(
            title = "Способ подачи сигнала при поиске автомобиля",
            values = mapOf(
                0 to "Выключено",
                538313729 to "Звук",
                538313730 to "Свет",
                538313731 to "Свет и звук",
            )
        ),
        "SETTING_FUNC_CDC_MODE" to EcarxFieldMetadata("Cdc режим"),
        "SETTING_FUNC_CDC_MODE_WARNING" to EcarxFieldMetadata("Cdc режим warning"),
        "SETTING_FUNC_CENTRAL_LOCK" to EcarxFieldMetadata("Центральный замок"),
        "SETTING_FUNC_CONGESTION_AHEAD_ALARM" to EcarxFieldMetadata("Пробка впереди предупреждение"),
        "SETTING_FUNC_CPM_SWITCH" to EcarxFieldMetadata("Cpm переключатель"),
        "SETTING_FUNC_CSD_POSITION" to EcarxFieldMetadata("Csd положение"),
        "SETTING_FUNC_DANGEROUS_ROAD_ALARM" to EcarxFieldMetadata("Dangerous road предупреждение"),
        "SETTING_FUNC_DANGEROUS_ROAD_ALARM_MODE" to EcarxFieldMetadata("Dangerous road предупреждение режим"),
        "SETTING_FUNC_DATA_COLLECTION" to EcarxFieldMetadata("Сбор телематических данных"),
        "SETTING_FUNC_DAYLIGHT_SAVING_TIME" to EcarxFieldMetadata("Летнее время переход время"),
        "SETTING_FUNC_DAYMODE_SETTING" to EcarxFieldMetadata(
            title = "Режим оформления день/ночь",
            values = mapOf(
                0 to "Выключено",
                538247425 to "День",
                538247426 to "Ночь",
                538247427 to "Авто",
                538247428 to "Пользовательский",
                538247429 to "По восходу/закату",
            )
        ),
        "SETTING_FUNC_DAYMODE_SYNC" to EcarxFieldMetadata("Синхронизация режима день/ночь"),
        "SETTING_FUNC_DIGITAL_KEY" to EcarxFieldMetadata("Цифровой ключ"),
        "SETTING_FUNC_DIGITAL_KEY_PAIRING_FAILED" to EcarxFieldMetadata("Цифровой ключ сопряжение ошибка"),
        "SETTING_FUNC_DIGITAL_KEY_REQ_STS" to EcarxFieldMetadata("Статус запроса цифрового ключа"),
        "SETTING_FUNC_DIGITAL_KEY_RES_TIMEOUT" to EcarxFieldMetadata("Цифровой ключ ответ тайм-аут"),
        "SETTING_FUNC_DIGITAL_KEY_SUSPENSION" to EcarxFieldMetadata("Приостановка цифрового ключа"),
        "SETTING_FUNC_DIGITAL_KEY_TERMINATION" to EcarxFieldMetadata("Завершение работы цифрового ключа"),
        "SETTING_FUNC_DIGITAL_KEY_TRACKING_RESULT" to EcarxFieldMetadata("Цифровой ключ отслеживание результат"),
        "SETTING_FUNC_DIGITAL_KEY_TRACKING_WAIT" to EcarxFieldMetadata("Цифровой ключ отслеживание ожидание"),
        "SETTING_FUNC_DIGITAL_KEY_UNPAIR" to EcarxFieldMetadata("Отвязка цифрового ключа"),
        "SETTING_FUNC_DIM_HOLIDAY_WALLPAPER" to EcarxFieldMetadata("Dim праздничные обои"),
        "SETTING_FUNC_DOOR_OPEN_WARN_ACTIVE" to EcarxFieldMetadata("Предупреждение об открытии двери"),
        "SETTING_FUNC_DOOR_OPEN_WARN_VOLUME" to EcarxFieldMetadata(
            title = "Громкость предупреждения об открытии двери",
            values = mapOf(
                0 to "Выключено",
                538051073 to "Низкая",
                538051074 to "Средняя",
                538051075 to "Высокая",
            )
        ),
        "SETTING_FUNC_DRIVER_ALERT_CONTROL" to EcarxFieldMetadata("Контроль внимания водителя"),
        "SETTING_FUNC_DRIVER_MODE_SOUND_SWITCH" to EcarxFieldMetadata("Водитель режим звук переключатель"),
        "SETTING_FUNC_DRIVER_PERFOR_PERMANENT" to EcarxFieldMetadata("Водитель характеристики permanent"),
        "SETTING_FUNC_DRIVER_PERFOR_SUPPORT" to EcarxFieldMetadata("Водитель характеристики поддержка"),
        "SETTING_FUNC_DRVR_SEB" to EcarxFieldMetadata("SEB водителя"),
        "SETTING_FUNC_EASY_INGRESS_EGRESS" to EcarxFieldMetadata("Облегчённая посадка/выход"),
        "SETTING_FUNC_EASY_INGRESS_EGRESS_MODE" to EcarxFieldMetadata("Режим облегчённой посадки/выхода"),
        "SETTING_FUNC_ELECTRIC_MILEAGE_DISPLAY_MODE" to EcarxFieldMetadata("Электрический запас хода отображение режим"),
        "SETTING_FUNC_ELECTRIC_MILEAGE_DISPLAY_SWITCH" to EcarxFieldMetadata("Электрический запас хода отображение переключатель"),
        "SETTING_FUNC_ELECTRONIC_PARKING" to EcarxFieldMetadata("Электронный стояночный тормоз"),
        "SETTING_FUNC_ELE_SEATBELT_COMFORT" to EcarxFieldMetadata("Ele ремень безопасности комфорт"),
        "SETTING_FUNC_EMERGENCY_VEHICLE_ALARM" to EcarxFieldMetadata("Экстренное автомобиля предупреждение"),
        "SETTING_FUNC_EMERGENCY_VEHICLE_ALARM_MODE" to EcarxFieldMetadata("Экстренное автомобиля предупреждение режим"),
        "SETTING_FUNC_EMGY_LANE_KEEP_AID" to EcarxFieldMetadata("Экстренное удержание в полосе"),
        "SETTING_FUNC_EMGY_LANE_OCC_WARNING" to EcarxFieldMetadata("Экстренное предупреждение о занятой полосе"),
        "SETTING_FUNC_ENERGY_PREDICTION_MSG" to EcarxFieldMetadata("Энергия прогноз msg"),
        "SETTING_FUNC_ENERGY_PREDICTION_OPTIMIZATION" to EcarxFieldMetadata("Энергия прогноз оптимизация"),
        "SETTING_FUNC_ENERGY_PREDICTION_SWITCH" to EcarxFieldMetadata("Энергия прогноз переключатель"),
        "SETTING_FUNC_ENERGY_REGENERATION" to EcarxFieldMetadata(
            title = "Уровень рекуперации",
            values = mapOf(
                0 to "Выключено",
                537003265 to "Низкая",
                537003266 to "Средняя",
                537003267 to "Высокая",
                537003268 to "Авто",
            )
        ),
        "SETTING_FUNC_ENGINE_MAINTENANCE_TIME_RESET" to EcarxFieldMetadata("Сброс времени обслуживания двигателя"),
        "SETTING_FUNC_ENGINE_STOP_START" to EcarxFieldMetadata("Старт-стоп двигателя"),
        "SETTING_FUNC_ENTER_AUTO_SHOW_MODE" to EcarxFieldMetadata("Вход автоматический показ режим"),
        "SETTING_FUNC_ENTER_AUTO_SHOW_MODE_RE" to EcarxFieldMetadata("Вход автоматический показ режим re"),
        "SETTING_FUNC_ENVIRONMENTAL_PROTECTION_LEVEL" to EcarxFieldMetadata("Экологический защита уровень"),
        "SETTING_FUNC_ESC_SPORT_MODE" to EcarxFieldMetadata("Спортивный режим ESC"),
        "SETTING_FUNC_ESM_SWITCH" to EcarxFieldMetadata("Звуковое оформление ESM"),
        "SETTING_FUNC_ESM_TYPE" to EcarxFieldMetadata(
            title = "Тип звука ESM",
            values = mapOf(
                0 to "Выключено",
                540281601 to "Spacewalk",
                540281602 to "Energy Pulse",
                540281603 to "Pixel",
            )
        ),
        "SETTING_FUNC_ESM_VOLUME" to EcarxFieldMetadata(
            title = "Громкость ESM",
            values = mapOf(
                0 to "Выключено",
                538575361 to "Низкая",
                538575362 to "Средняя",
                538575363 to "Высокая",
            )
        ),
        "SETTING_FUNC_EVASIVE_MANEUVER_AID" to EcarxFieldMetadata("Ассистент уклоняющего манёвра"),
        "SETTING_FUNC_EXTERNAL_ARTIFICIAL_SOUND_SWITCH" to EcarxFieldMetadata("Внешний искусственный звук переключатель"),
        "SETTING_FUNC_EXTERNAL_ARTIFICIAL_SOUND_TYPE" to EcarxFieldMetadata("Внешний искусственный звук тип"),
        "SETTING_FUNC_EYE_BALL_TRACK" to EcarxFieldMetadata("Отслеживание взгляда"),
        "SETTING_FUNC_E_PEDAL" to EcarxFieldMetadata("Однопедальный режим"),
        "SETTING_FUNC_FACE_CAMERA_COVER" to EcarxFieldMetadata("Лицо камера cover"),
        "SETTING_FUNC_FACE_RECOGNITION" to EcarxFieldMetadata("Распознавание лица"),
        "SETTING_FUNC_FACE_RECOGNITION_RESULT" to EcarxFieldMetadata("Результат распознавания лица"),
        "SETTING_FUNC_FACIAL_RECOGNITION" to EcarxFieldMetadata("Система распознавания лица"),
        "SETTING_FUNC_FORWARD_COLLISION_WARN" to EcarxFieldMetadata("Предупреждение о фронтальном столкновении"),
        "SETTING_FUNC_FORWARD_COLLISION_WARN_SNVTY" to EcarxFieldMetadata(
            title = "Чувствительность предупреждения о столкновении",
            values = mapOf(
                0 to "Выключено",
                537788929 to "Низкая",
                537788930 to "Средняя",
                537788931 to "Высокая",
            )
        ),
        "SETTING_FUNC_FRONT_CROSS_TRAFFIC_ALERT" to EcarxFieldMetadata("Предупреждение о поперечном движении спереди"),
        "SETTING_FUNC_FRONT_WIPER_IDLE" to EcarxFieldMetadata("Передний wiper idle"),
        "SETTING_FUNC_GLOVEBOX_LOCK" to EcarxFieldMetadata(
            title = "Бардачок замок",
            values = mapOf(
                537854720 to "Ожидание",
                537854721 to "Заблокировать",
                537854722 to "Разблокировать",
            )
        ),
        "SETTING_FUNC_HDC_SWITCH" to EcarxFieldMetadata("Система помощи при спуске (HDC)"),
        "SETTING_FUNC_HEAD_RESTRAINT_AUDIO" to EcarxFieldMetadata("Подголовник подголовник аудио"),
        "SETTING_FUNC_HEAD_RESTRAINT_AUDIO_TYPE" to EcarxFieldMetadata("Подголовник подголовник аудио тип"),
        "SETTING_FUNC_HILL_START_ASSIST" to EcarxFieldMetadata("Помощь при трогании на подъёме"),
        "SETTING_FUNC_HMI_THEMES_CHANGE" to EcarxFieldMetadata(
            title = "Тема интерфейса",
            values = mapOf(
                536936705 to "Clear",
                536936706 to "Louder",
                536936707 to "Inter",
                536936708 to "Hyper",
            )
        ),
        "SETTING_FUNC_HOLOGRAPHIC_ACTIVATED" to EcarxFieldMetadata("Holographic activated"),
        "SETTING_FUNC_HOLOGRAPHIC_BACKLIGHT_LEVEL" to EcarxFieldMetadata("Holographic backlight уровень"),
        "SETTING_FUNC_HOLOGRAPHIC_BACKLIGHT_MODE" to EcarxFieldMetadata("Holographic backlight режим"),
        "SETTING_FUNC_HUD_ACTIVE" to EcarxFieldMetadata("Проекционный дисплей"),
        "SETTING_FUNC_HUD_CALIBRATION" to EcarxFieldMetadata("Калибровка HUD"),
        "SETTING_FUNC_HV_BATT_EGY_SOC" to EcarxFieldMetadata("Hv батарея egy soc"),
        "SETTING_FUNC_HV_BATT_HEAT_POP" to EcarxFieldMetadata("Hv батарея нагрев pop"),
        "SETTING_FUNC_HV_BATT_HEAT_TOAST" to EcarxFieldMetadata("Hv батарея нагрев toast"),
        "SETTING_FUNC_INTELLIGENT_FUEL_SAVE" to EcarxFieldMetadata("Интеллектуальное энергосбережение/экономия топлива"),
        "SETTING_FUNC_INTERNAL_COMMUNICATION" to EcarxFieldMetadata("Внутренняя связь"),
        "SETTING_FUNC_INTERNAL_COMMUNICATION_VOLUME" to EcarxFieldMetadata("Внутренняя связь громкость"),
        "SETTING_FUNC_JOURNAL_LOGS" to EcarxFieldMetadata("Журналирование / системные логи"),
        "SETTING_FUNC_KEYLESS_UNLOCKING" to EcarxFieldMetadata(
            title = "Бесключевое отпирание",
            values = mapOf(
                0 to "Выключено",
                537920513 to "Все двери",
                537920514 to "Только одна дверь",
            )
        ),
        "SETTING_FUNC_LAMP_ADAPTIVE_FRONT_LIGHT" to EcarxFieldMetadata("Адаптивный передний свет"),
        "SETTING_FUNC_LAMP_APPROACH_LIGHT" to EcarxFieldMetadata("Подсветка при приближении"),
        "SETTING_FUNC_LAMP_AUTOLIGHT" to EcarxFieldMetadata(
            title = "Автоматический свет",
            values = mapOf(
                537133825 to "Позже",
                537133826 to "Обычно",
                537133827 to "Раньше",
            )
        ),
        "SETTING_FUNC_LAMP_AUTOMATIC_COURTESY_LIGHT" to EcarxFieldMetadata("Свет автоматический салонный свет"),
        "SETTING_FUNC_LAMP_AUX_HIGHBEAM" to EcarxFieldMetadata("Свет дополнительный дальний свет"),
        "SETTING_FUNC_LAMP_BENDINGLIGHT" to EcarxFieldMetadata("Поворотный свет"),
        "SETTING_FUNC_LAMP_CORNERING_LIGHT" to EcarxFieldMetadata("Подсветка поворотов"),
        "SETTING_FUNC_LAMP_DAYTIME_RUNNING_LIGHT" to EcarxFieldMetadata("Дневные ходовые огни"),
        "SETTING_FUNC_LAMP_EXTERIOR_LIGHT_CONTROL" to EcarxFieldMetadata(
            title = "Режим наружного освещения",
            values = mapOf(
                0 to "Выключено",
                537136641 to "Габариты",
                537136642 to "Ближний свет",
                537136643 to "Авто",
                537136644 to "Автоматический дальний / AHBC",
            )
        ),
        "SETTING_FUNC_LAMP_HIGHBEAM_ACTIVE" to EcarxFieldMetadata(
            title = "Скорость/чувствительность автоматического дальнего",
            values = mapOf(
                537133569 to "Позднее/медленно",
                537133570 to "Обычно",
                537133571 to "Раньше/быстро",
            )
        ),
        "SETTING_FUNC_LAMP_HOME_SAFE_LIGHT" to EcarxFieldMetadata(
            title = "Задержка света «Проводи домой»",
            values = mapOf(
                0 to "Выключено",
                537134849 to "30 секунд",
                537134850 to "60 секунд",
                537134851 to "90 секунд",
            )
        ),
        "SETTING_FUNC_LAMP_TRIPLE_FLASH" to EcarxFieldMetadata("Тройное мигание поворотником"),
        "SETTING_FUNC_LANE_CHANGE_ASSIST" to EcarxFieldMetadata("Ассистент смены полосы"),
        "SETTING_FUNC_LANE_CHANGE_WARING" to EcarxFieldMetadata("Предупреждение при смене полосы"),
        "SETTING_FUNC_LANE_CHANGE_WARNING_MODE" to EcarxFieldMetadata(
            title = "Режим предупреждения при смене полосы",
            values = mapOf(
                0 to "Выключено",
                537330705 to "Визуально",
                537330706 to "Звуком",
                537330707 to "Визуально и звуком",
            )
        ),
        "SETTING_FUNC_LANE_CHANGE_WARNING_SOUND" to EcarxFieldMetadata(
            title = "Громкость предупреждения при смене полосы",
            values = mapOf(
                0 to "Выключено",
                537330689 to "Низкая",
                537330690 to "Средняя",
                537330691 to "Высокая",
            )
        ),
        "SETTING_FUNC_LANE_KEEPING_AID" to EcarxFieldMetadata("Удержание в полосе"),
        "SETTING_FUNC_LANE_KEEPING_AID_MODE" to EcarxFieldMetadata(
            title = "Режим удержания в полосе",
            values = mapOf(
                0 to "Выключено",
                537330177 to "Предупреждение + вмешательство",
                537330178 to "Вмешательство",
                537330179 to "Только предупреждение",
            )
        ),
        "SETTING_FUNC_LANE_KEEPING_AID_WARNING" to EcarxFieldMetadata(
            title = "Тип предупреждения удержания в полосе",
            values = mapOf(
                0 to "Выключено",
                537330945 to "Звук",
                537330946 to "Вибрация",
                537330947 to "Звук и вибрация",
            )
        ),
        "SETTING_FUNC_LAUNCH_MODE" to EcarxFieldMetadata("Launch режим"),
        "SETTING_FUNC_LAUNCH_MODE_INDCN" to EcarxFieldMetadata("Launch режим indcn"),
        "SETTING_FUNC_LEFT_TURN_ASSIST_ALARM" to EcarxFieldMetadata("Левый поворот ассистент предупреждение"),
        "SETTING_FUNC_LEFT_TURN_ASSIST_ALARM_MODE" to EcarxFieldMetadata("Левый поворот ассистент предупреждение режим"),
        "SETTING_FUNC_LIFE_DETECTION" to EcarxFieldMetadata("Обнаружение присутствия/живого объекта"),
        "SETTING_FUNC_LOCK_REAR_SEAT_DISPLAY" to EcarxFieldMetadata("Замок задний сиденье отображение"),
        "SETTING_FUNC_LOCK_RFDM_REMOTE_CONTROLLER" to EcarxFieldMetadata("Замок rfdm удалённый controller"),
        "SETTING_FUNC_MAINTENANCE_MILEAGE_RESET" to EcarxFieldMetadata("Сброс сервисного пробега"),
        "SETTING_FUNC_MAINTENANCE_TIME_RESET" to EcarxFieldMetadata("Сброс сервисного интервала по времени"),
        "SETTING_FUNC_MANUAL_TRAILER_LAMP_CHECK" to EcarxFieldMetadata("Ручная проверка фонарей прицепа"),
        "SETTING_FUNC_MIRROR_AUTO_FOLDING" to EcarxFieldMetadata("Автоскладывание зеркал"),
        "SETTING_FUNC_MIRROR_DIMMING" to EcarxFieldMetadata(
            title = "Автозатемнение зеркала",
            values = mapOf(
                0 to "Выключено",
                537460993 to "Сильное затемнение",
                537460994 to "Обычное",
                537460995 to "Слабое затемнение",
            )
        ),
        "SETTING_FUNC_MIRROR_DIPPING" to EcarxFieldMetadata(
            title = "Опускание зеркал при манёврах",
            values = mapOf(
                0 to "Выключено",
                537461505 to "Водительское зеркало",
                537461506 to "Пассажирское зеркало",
                537461507 to "Оба зеркала",
            )
        ),
        "SETTING_FUNC_MIRROR_DIPPING_SWITCH" to EcarxFieldMetadata("Автоопускание зеркал"),
        "SETTING_FUNC_MULTIMEDIA_GESTURE" to EcarxFieldMetadata("Мультимедиа жест"),
        "SETTING_FUNC_MULTI_FUNC_KNOB_DIRECTION" to EcarxFieldMetadata("Multi func регулятор направление"),
        "SETTING_FUNC_MULTI_FUNC_KNOB_PRESS_STATUS" to EcarxFieldMetadata("Multi func регулятор нажатие status"),
        "SETTING_FUNC_MULTI_FUNC_KNOB_ROTATE_STEP" to EcarxFieldMetadata("Multi func регулятор вращение шаг"),
        "SETTING_FUNC_MUSIC_GESTURE" to EcarxFieldMetadata("Музыка жест"),
        "SETTING_FUNC_PARK_ASSIST_SYS_ACTIVATED" to EcarxFieldMetadata("Система помощи при парковке"),
        "SETTING_FUNC_PARK_ASSIST_SYS_VOLUME" to EcarxFieldMetadata(
            title = "Громкость парковочного ассистента",
            values = mapOf(
                0 to "Выключено",
                537723393 to "Низкая",
                537723394 to "Средняя",
                537723395 to "Высокая",
            )
        ),
        "SETTING_FUNC_PARK_COMFORT_BELT_DOOR_OPEN" to EcarxFieldMetadata("Парковка комфорт belt дверь открытие"),
        "SETTING_FUNC_PARK_COMFORT_MODE_COUNTDOWN_TIMER" to EcarxFieldMetadata("Парковка комфорт режим обратный отсчёт timer"),
        "SETTING_FUNC_PARK_COMFORT_MODE_OFF_REASON" to EcarxFieldMetadata("Парковка комфорт режим выключение причина"),
        "SETTING_FUNC_PARK_COMFORT_MODE_TIMER" to EcarxFieldMetadata("Парковка комфорт режим timer"),
        "SETTING_FUNC_PARK_COMFORT_MODE_TIMER_MAX" to EcarxFieldMetadata("Парковка комфорт режим timer максимум"),
        "SETTING_FUNC_PARK_COMFORT_MODE_TIMER_MIN" to EcarxFieldMetadata("Парковка комфорт режим timer минимум"),
        "SETTING_FUNC_PARK_COMFORT_MODE_TIMER_STEP" to EcarxFieldMetadata("Парковка комфорт режим timer шаг"),
        "SETTING_FUNC_PASSENGER_AIRBAG" to EcarxFieldMetadata("Подушка безопасности пассажира"),
        "SETTING_FUNC_PASSIVE_ARMING" to EcarxFieldMetadata("Автоматическая постановка на охрану"),
        "SETTING_FUNC_PBC_AUTO_APPLY" to EcarxFieldMetadata("Автоматическое включение парковочного тормоза"),
        "SETTING_FUNC_PBC_DOUBLE_EPB_SWITCH" to EcarxFieldMetadata("Двойная команда EPB"),
        "SETTING_FUNC_PBC_EPB_SWITCH" to EcarxFieldMetadata("Управление EPB"),
        "SETTING_FUNC_PCM_TIMER" to EcarxFieldMetadata(
            title = "Pcm timer",
            values = mapOf(
                0 to "Выключено",
                538640641 to "15 минут",
                538640642 to "30 минут",
                538640643 to "45 минут",
                538640644 to "60 минут",
                538640645 to "90 минут",
                538640646 to "120 минут",
            )
        ),
        "SETTING_FUNC_PDC_SWITCH" to EcarxFieldMetadata("Парктроники / PDC"),
        "SETTING_FUNC_PEB_MODE" to EcarxFieldMetadata(
            title = "Peb режим",
            values = mapOf(
                0 to "Выключено",
                537264641 to "PEB",
                537264642 to "MSP",
            )
        ),
        "SETTING_FUNC_PGEAR_UNLOCK" to EcarxFieldMetadata("Разблокировка P"),
        "SETTING_FUNC_PRIVATE_LOCK" to EcarxFieldMetadata("Приватная блокировка"),
        "SETTING_FUNC_PRIVATE_LOCK_REMINDER" to EcarxFieldMetadata("Напоминание приватной блокировки"),
        "SETTING_FUNC_PSD_SCREEN_SWITCH" to EcarxFieldMetadata("Psd экран переключатель"),
        "SETTING_FUNC_RAIN_SENSOR_SENSITIVITY" to EcarxFieldMetadata(
            title = "Чувствительность датчика дождя",
            values = mapOf(
                0 to "Уровень 1",
                1 to "Уровень 2",
                2 to "Уровень 3",
                3 to "Уровень 4",
                4 to "Уровень 5",
                5 to "Уровень 6",
                6 to "Уровень 7",
            )
        ),
        "SETTING_FUNC_REAR_COLLISION_WARNING" to EcarxFieldMetadata("Предупреждение о заднем столкновении"),
        "SETTING_FUNC_REAR_CROSS_TRAFFIC_ALERT" to EcarxFieldMetadata("Предупреждение о поперечном движении сзади"),
        "SETTING_FUNC_REAR_MIRROR_STREAM" to EcarxFieldMetadata("Задний зеркало видеопоток"),
        "SETTING_FUNC_REAR_MIRR_STREAM_SWITCH" to EcarxFieldMetadata("Задний mirr видеопоток переключатель"),
        "SETTING_FUNC_REAR_MIRR_STREAM_VERTICAL_VISUAL" to EcarxFieldMetadata("Задний mirr видеопоток вертикальное изображение"),
        "SETTING_FUNC_REAR_MIRR_STREAM_VERTICAL_VISUAL_MAX" to EcarxFieldMetadata("Задний mirr видеопоток вертикальное изображение максимум"),
        "SETTING_FUNC_REAR_MIRR_STREAM_VERTICAL_VISUAL_MIN" to EcarxFieldMetadata("Задний mirr видеопоток вертикальное изображение минимум"),
        "SETTING_FUNC_REAR_MIRR_STREAM_VERTICAL_VISUAL_STEP" to EcarxFieldMetadata("Задний mirr видеопоток вертикальное изображение шаг"),
        "SETTING_FUNC_REAR_MIRR_STREAM_ZOOM_LEVEL" to EcarxFieldMetadata("Задний mirr видеопоток масштаб уровень"),
        "SETTING_FUNC_REAR_SPOILER_ADJUST" to EcarxFieldMetadata(
            title = "Положение заднего спойлера",
            values = mapOf(
                0 to "Выключено",
                538510337 to "Положение 1",
                538510338 to "Положение 2",
            )
        ),
        "SETTING_FUNC_REAR_SPOILER_ADJUST_FAIL" to EcarxFieldMetadata("Задний спойлер регулировка fail"),
        "SETTING_FUNC_REAR_SPOILER_POSITION_ADJUST_MODE" to EcarxFieldMetadata("Задний спойлер положение регулировка режим"),
        "SETTING_FUNC_REAR_SPOILER_POSN_REQUEST" to EcarxFieldMetadata("Задний спойлер posn запрос"),
        "SETTING_FUNC_REAR_WINDOW_CLEAN" to EcarxFieldMetadata("Задний окно очистка"),
        "SETTING_FUNC_REDUCED_GUARD" to EcarxFieldMetadata("Уменьшенный режим охраны"),
        "SETTING_FUNC_RED_LIGHT_ALARM" to EcarxFieldMetadata("Красный свет предупреждение"),
        "SETTING_FUNC_RED_LIGHT_ALARM_MODE" to EcarxFieldMetadata("Красный свет предупреждение режим"),
        "SETTING_FUNC_REFUELING_SWT" to EcarxFieldMetadata("Разблокировка лючка заправки"),
        "SETTING_FUNC_REMOTE_DIAGNOSTICS" to EcarxFieldMetadata("Удалённая диагностика"),
        "SETTING_FUNC_REMOTE_UNLOCKING" to EcarxFieldMetadata("Удалённое отпирание"),
        "SETTING_FUNC_RESET_SETTINGS_DEFAULT" to EcarxFieldMetadata("Сброс настроек автомобиля"),
        "SETTING_FUNC_REVERSE_OVERTAKING_ALARM" to EcarxFieldMetadata("Задний ход обгон предупреждение"),
        "SETTING_FUNC_REVERSE_OVERTAKING_ALARM_MODE" to EcarxFieldMetadata("Задний ход обгон предупреждение режим"),
        "SETTING_FUNC_RMS_ACTIVE" to EcarxFieldMetadata("Rms активно"),
        "SETTING_FUNC_ROTATED_WHEELS_WARNING" to EcarxFieldMetadata("Предупреждение о вывернутых колёсах"),
        "SETTING_FUNC_ROTATED_WHEELS_WARNING_INFO" to EcarxFieldMetadata("Направление вывернутых колёс"),
        "SETTING_FUNC_RSD_SWITCH" to EcarxFieldMetadata("Rsd переключатель"),
        "SETTING_FUNC_RVDC" to EcarxFieldMetadata("Rvdc"),
        "SETTING_FUNC_SAILING_MODE" to EcarxFieldMetadata("Режим движения накатом"),
        "SETTING_FUNC_SAY_HI" to EcarxFieldMetadata("Сказать привет"),
        "SETTING_FUNC_SCREEN_SAVER_CUSTOM_NAME" to EcarxFieldMetadata("Имя в пользовательской заставке"),
        "SETTING_FUNC_SCREEN_SAVER_CUSTOM_PICTURE" to EcarxFieldMetadata("Изображение пользовательской заставки"),
        "SETTING_FUNC_SCREEN_SAVER_CUSTOM_TEXT" to EcarxFieldMetadata("Текст пользовательской заставки"),
        "SETTING_FUNC_SCREEN_SAVER_STYLE" to EcarxFieldMetadata("Стиль заставки"),
        "SETTING_FUNC_SCREEN_SAVER_TIME" to EcarxFieldMetadata(
            title = "Таймер заставки",
            values = mapOf(
                539035393 to "5 минут",
                539035394 to "10 минут",
                539035395 to "Никогда",
            )
        ),
        "SETTING_FUNC_SEATBELT_WARNING_SOUND" to EcarxFieldMetadata("Звук предупреждения ремня безопасности"),
        "SETTING_FUNC_SEB_POP" to EcarxFieldMetadata("Статус/сообщение SEB"),
        "SETTING_FUNC_SET_WALLPAPER_TO_DIM" to EcarxFieldMetadata("Set обои to dim"),
        "SETTING_FUNC_SOUND_WARNING_VOLUME" to EcarxFieldMetadata("Громкость системных предупреждений"),
        "SETTING_FUNC_SPEED_CONTROL" to EcarxFieldMetadata("Контроль скорости"),
        "SETTING_FUNC_SPEED_CONTROL_MODE" to EcarxFieldMetadata("Режим контроля скорости"),
        "SETTING_FUNC_SPEED_GUIDANCE_ALARM" to EcarxFieldMetadata("Speed подсказка предупреждение"),
        "SETTING_FUNC_SPEED_LIMITATION" to EcarxFieldMetadata("Ограничитель скорости"),
        "SETTING_FUNC_SPEED_LIMITATION_MODE" to EcarxFieldMetadata("Режим ограничителя скорости"),
        "SETTING_FUNC_SPEED_LOCKING" to EcarxFieldMetadata("Запирание на скорости"),
        "SETTING_FUNC_STEERING_ASSISTANCE_LEVEL" to EcarxFieldMetadata("Уровень усилителя руля"),
        "SETTING_FUNC_STEERING_WHEEL_ANGLE_WARN_SWITCH" to EcarxFieldMetadata("Рулевое управление руль угол предупреждение переключатель"),
        "SETTING_FUNC_SUNROOF_TRANSPARENCY_AUTO" to EcarxFieldMetadata("Люк прозрачность автоматический"),
        "SETTING_FUNC_SUPER_POWER_SAVING" to EcarxFieldMetadata("Супер энергосбережение переход"),
        "SETTING_FUNC_SUSPENSION_DEACTIVATION_DAMPENING" to EcarxFieldMetadata("Отключение демпфирования подвески"),
        "SETTING_FUNC_SUSPENSION_DRIVER_ENTRY_CONTROL" to EcarxFieldMetadata("Положение подвески для посадки водителя"),
        "SETTING_FUNC_SUSPENSION_HEIGHT_ADJUST" to EcarxFieldMetadata("Регулировка высоты подвески"),
        "SETTING_FUNC_TCAM_5G_SWITCH" to EcarxFieldMetadata("5G-модем TCAM"),
        "SETTING_FUNC_TCAM_RESET" to EcarxFieldMetadata("Сброс TCAM"),
        "SETTING_FUNC_TEM_PROVISIONING_STATE" to EcarxFieldMetadata("Tem провижининг state"),
        "SETTING_FUNC_THREE_SCREEN_ANIMATION" to EcarxFieldMetadata("Три экран анимация"),
        "SETTING_FUNC_TRACK_GESTURE" to EcarxFieldMetadata("Трек жест"),
        "SETTING_FUNC_TRACK_MODE" to EcarxFieldMetadata("Трек режим"),
        "SETTING_FUNC_TRAFFIC_LIGHT_ATTENTION" to EcarxFieldMetadata("Контроль сигналов светофора"),
        "SETTING_FUNC_TRAFFIC_SIGN_RECOGNITION" to EcarxFieldMetadata("Распознавание дорожных знаков"),
        "SETTING_FUNC_TRAFFIC_SIGN_RECOGNITION_ALERT" to EcarxFieldMetadata("Предупреждения распознавания дорожных знаков"),
        "SETTING_FUNC_TRAILER_MODE" to EcarxFieldMetadata("Режим прицепа"),
        "SETTING_FUNC_TWOSTEP_UNLOCKING" to EcarxFieldMetadata("Двухэтапное отпирание"),
        "SETTING_FUNC_UNLOCK_P_GEAR" to EcarxFieldMetadata("Разрешение разблокировки передачи P"),
        "SETTING_FUNC_VEHICLE_SAFETY_ALARM" to EcarxFieldMetadata("Автомобиля safety предупреждение"),
        "SETTING_FUNC_VEHICLE_SAFETY_ALARM_MODE" to EcarxFieldMetadata("Автомобиля safety предупреждение режим"),
        "SETTING_FUNC_VISIBLE_LOCKING_FEEDBACK" to EcarxFieldMetadata("Световое подтверждение запирания"),
        "SETTING_FUNC_VISIBLE_UNLOCKING_FEEDBACK" to EcarxFieldMetadata("Световое подтверждение отпирания"),
        "SETTING_FUNC_VOICE_CONTROL_LOCKING" to EcarxFieldMetadata("Голос управление запирание"),
        "SETTING_FUNC_VOICE_KEY_DISTANCE" to EcarxFieldMetadata("Голос ключ distance"),
        "SETTING_FUNC_VOICE_POWER_MODE_SET" to EcarxFieldMetadata("Голос энергосбережение режим set"),
        "SETTING_FUNC_VOICE_RECOGNITION" to EcarxFieldMetadata("Голос распознавание"),
        "SETTING_FUNC_VOICE_SEARCH_KEY" to EcarxFieldMetadata("Голос поиск ключ"),
        "SETTING_FUNC_VOLUME_LIMIT" to EcarxFieldMetadata("Ограничение громкости"),
        "SETTING_FUNC_VOLUME_LIMIT_MAX" to EcarxFieldMetadata("Максимальная громкость"),
        "SETTING_FUNC_VSTD_FAIL_TO_OPEN_TELM" to EcarxFieldMetadata("Vstd fail to открытие telm"),
        "SETTING_FUNC_VSTD_VFC_VEHICLE_SENTRY_FT_DET_CH" to EcarxFieldMetadata("Vstd vfc автомобиля sentry ft det ch"),
        "SETTING_FUNC_VSTD_VFC_VEHICLE_SENTRY_FT_DET_PS" to EcarxFieldMetadata("Vstd vfc автомобиля sentry ft det ps"),
        "SETTING_FUNC_VSTD_VFC_VEHICLE_SENTRY_FT_DET_SV" to EcarxFieldMetadata("Vstd vfc автомобиля sentry ft det sv"),
        "SETTING_FUNC_VSTD_VIDEO_UPLOAD_STATUS" to EcarxFieldMetadata("Vstd video upload status"),
        "SETTING_FUNC_WAITING_MODE" to EcarxFieldMetadata("Ожидание режим"),
        "SETTING_FUNC_WALLPAPER_FESTIVAL_TYPE" to EcarxFieldMetadata("Обои festival тип"),
        "SETTING_FUNC_WALLPAPER_SYNC" to EcarxFieldMetadata("Обои синхронизация"),
        "SETTING_FUNC_WALLPAPER_SYNC_STYLE" to EcarxFieldMetadata("Обои синхронизация стиль"),
        "SETTING_FUNC_WELCOME_SOUND" to EcarxFieldMetadata("Приветственный звук"),
        "SETTING_FUNC_WELCOME_SOUND_TYPE" to EcarxFieldMetadata("Тип приветственного звука"),
        "SETTING_FUNC_WINDOW_CLOSE_SUNCURTAIN" to EcarxFieldMetadata("Закрытие шторки вместе с окном/люком"),
        "SETTING_FUNC_WINDOW_PINCH_WARN" to EcarxFieldMetadata("Предупреждение защиты от защемления стеклом"),
        "SETTING_FUNC_WINDOW_TRANSPARENCY_AUTO" to EcarxFieldMetadata("Окно прозрачность автоматический"),
        "SETTING_FUNC_WINDOW_VENTILATE" to EcarxFieldMetadata("Проветривание через окна"),
        "SETTING_FUNC_WINDSCREEN_SERVICE_POSITION" to EcarxFieldMetadata("Сервисное положение дворников"),
        "SETTING_FUNC_XCALL_KEY_LOCK" to EcarxFieldMetadata("Xcall ключ замок"),
    )

    val commonValueKeys: Set<String> = setOf(
        "HVAC_FUNC_POWER",
        "HVAC_FUNC_AUTO",
        "HVAC_FUNC_AC",
        "HVAC_FUNC_SEAT_MASSAGE_SWITCH",
        "HVAC_FUNC_ECO_SWITCH",
        "HVAC_FUNC_IONS_SWITCH",
        "HVAC_FUNC_AUTO_STEERING_WHEEL_HEAT_SWITCH",
        "HVAC_FUNC_AUTO_CONTROL",
        "SETTING_FUNC_ENGINE_STOP_START",
        "SETTING_FUNC_DRIVER_ALERT_CONTROL",
        "SETTING_FUNC_SPEED_CONTROL",
        "SETTING_FUNC_LAMP_DAYTIME_RUNNING_LIGHT",
        "SETTING_FUNC_PDC_SWITCH",
        "SETTING_FUNC_AUTO_HOLD",
        "SETTING_FUNC_HDC_SWITCH",
        "SETTING_FUNC_PBC_EPB_SWITCH",
        "SETTING_FUNC_PBC_DOUBLE_EPB_SWITCH",
        "SETTING_FUNC_LANE_KEEPING_AID",
        "SETTING_FUNC_LANE_CHANGE_ASSIST",
        "SETTING_FUNC_EMGY_LANE_OCC_WARNING",
        "SETTING_FUNC_AUTONOMOUS_EMERGENCY_BRAKING",
        "SETTING_FUNC_REAR_COLLISION_WARNING",
        "SETTING_FUNC_MIRROR_AUTO_FOLDING",
        "SETTING_FUNC_MIRROR_DIPPING_SWITCH",
        "SETTING_FUNC_TRAFFIC_SIGN_RECOGNITION",
        "SETTING_FUNC_PARK_ASSIST_SYS_ACTIVATED",
        "SETTING_FUNC_REMOTE_UNLOCKING",
        "SETTING_FUNC_SPEED_LOCKING",
        "SETTING_FUNC_TWOSTEP_UNLOCKING",
        "SETTING_FUNC_HUD_ACTIVE",
        "SETTING_FUNC_DOOR_OPEN_WARN_ACTIVE",
        "SETTING_FUNC_RMS_ACTIVE",
        "SETTING_FUNC_DAYMODE_SYNC",
        "SETTING_FUNC_TCAM_5G_SWITCH",
        "SETTING_FUNC_SUSPENSION_DRIVER_ENTRY_CONTROL",
        "SETTING_FUNC_ESM_SWITCH",
        "SETTING_FUNC_ARTIFICIAL_SOUND_SWITCH",
        "SETTING_FUNC_AVAS_SWITCH",
        "SETTING_FUNC_EXTERNAL_ARTIFICIAL_SOUND_SWITCH",
        "SETTING_FUNC_ROTATED_WHEELS_WARNING",
        "SETTING_FUNC_ENERGY_PREDICTION_SWITCH",
        "SETTING_FUNC_WALLPAPER_SYNC",
        "SETTING_FUNC_REAR_MIRR_STREAM_SWITCH",
        "SETTING_FUNC_REMOTE_DIAGNOSTICS",
        "SETTING_FUNC_HILL_START_ASSIST",
        "SETTING_FUNC_ELECTRIC_MILEAGE_DISPLAY_SWITCH",
        "SETTING_FUNC_DRIVER_MODE_SOUND_SWITCH",
        "SETTING_FUNC_STEERING_WHEEL_ANGLE_WARN_SWITCH",
        "SETTING_FUNC_ABNORMAL_VEHICLE_ALARM",
        "SETTING_FUNC_DANGEROUS_ROAD_ALARM",
        "SETTING_FUNC_EMERGENCY_VEHICLE_ALARM",
        "SETTING_FUNC_CONGESTION_AHEAD_ALARM",
        "SETTING_FUNC_SPEED_GUIDANCE_ALARM",
        "SETTING_FUNC_RED_LIGHT_ALARM",
        "SETTING_FUNC_VEHICLE_SAFETY_ALARM",
        "SETTING_FUNC_PSD_SCREEN_SWITCH",
        "SETTING_FUNC_REVERSE_OVERTAKING_ALARM",
        "SETTING_FUNC_LEFT_TURN_ASSIST_ALARM",
        "SETTING_FUNC_HOLOGRAPHIC_ACTIVATED",
        "SETTING_FUNC_CPM_SWITCH",
        "SETTING_FUNC_RSD_SWITCH",
        "SETTING_FUNC_VOICE_CONTROL_LOCKING",
        "SETTING_FUNC_CDC_MODE_WARNING",
        "BCM_FUNC_LIGHT_FRONT_FOG_LAMPS",
        "BCM_FUNC_LIGHT_REAR_FOG_LAMPS",
        "BCM_FUNC_LIGHT_HAZARD_FLASHERS",
        "BCM_FUNC_LIGHT_ATMOSPHERE_LAMPS",
        "BCM_FUNC_LIGHT_READING_LIGHT",
        "BCM_FUNC_ALL_READING_LIGHTS_SWITCH",
        "BCM_FUNC_SUNROOF_ININ_SWITCH",
        "BCM_FUNC_DIM_ZONE_A_WARNING",
    )
}
